### ISSUE TITLE
PDF of Schematic?

### ISSUE THREAD

**Issue by neubauek** [python-ugame/ugame-10-hardware#3]
Hello,
I was looking at making a derivative of the uGame 10 hardware using my CircuitBrains Deluxe module that has an ATSAMD51. I was wondering if you would be willing to put a PDF of the Fritzing schematic in this repository. I downloaded Fritzing and your repository, but am having trouble getting it to open correctly. It complains about missing parts.

Thank you,
Kevin

**Comment by deshipu** [comment]
The SVG at https://github.com/python-ugame/ugame-10-hardware/blob/master/ugame-10_schem.svg is not good for you?

**Comment by deshipu** [comment]
By the way, I highly recommend looking at https://github.com/pewpew-game/pewpew-m4-v8 rather than µGame — SAMD51 is much more suitable for this.

**Comment by neubauek** [comment]
Thank you for the info. I had not seen that schematic file or the pewpew M4.
